force-app/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The date the opportunity&apos;s product ends</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Signatory__c.field-meta.xml
<CustomField>
    <fullName>Signatory__c</fullName>
    <description>Listing of common (04-1-2021) signatories</description>
    <inlineHelpText>Choose a signatory for the contract</inlineHelpText>
    <label>Signatory</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Jeremy Singer</fullName>
            </value>
            <value>
                <fullName>David C. Meade Jr.</fullName>
            </value>
            <value>
                <fullName>Tarlin Ray</fullName>
            </value>
            <value>
                <fullName>Doug Waugh</fullName>
            </value>
            <value>
                <fullName>Aaron Lemmon-Strauss</fullName>
            </value>
            <value>
                <fullName>Dr. Eldon Tyrell</fullName>
                <isActive>false</isActive>
                <label>Dr. Eldon Tyrell</label>
            </value>
            <value>
                <fullName>Hannibal Chew</fullName>
                <isActive>false</isActive>
                <label>Hannibal Chew</label>
            </value>
            <value>
                <fullName>J.F. Sebastian</fullName>
                <isActive>false</isActive>
                <label>J.F. Sebastian</label>
            </value>
            <value>
                <fullName>Leon Kowalski</fullName>
                <isActive>false</isActive>
                <label>Leon Kowalski</label>
            </value>
            <value>
                <fullName>Niander Wallace</fullName>
                <isActive>false</isActive>
                <label>Niander Wallace</label>
            </value>
            <value>
                <fullName>Rick Deckard</fullName>
                <isActive>false</isActive>
                <label>Rick Deckard</label>
            </value>
            <value>
                <fullName>Sapper Morton</fullName>
                <isActive>false</isActive>
                <label>Sapper Morton</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date the opportunity starts</description>
    <inlineHelpText>Please enter start date</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TestOpExtController.cls
@isTest(SeeAllData=true)
public with sharing class TestOpExtController {
    private Opportunity Op;

    public TestOpExtController() {

    }

    @IsTest(SeeAllData=true)
    static void TestGenerateSFJSON(){
        Opportunity selOp;

        //  There's only 1 Opportunity so I don't need the ID to retrieve the right opportunity
        selOp = [SELECT 
        Account.Name,
        Start_Date__c,
        End_Date__c,
        Signatory__c,
        CloseDate,
        Amount,
        Account.Type
        FROM Opportunity];
       
        ApexPages.StandardController sc = new ApexPages.StandardController(selOp);
        OpportunityJsonControllerExtension OpJsonExt = new OpportunityJsonControllerExtension(sc);

        //  Invoke the routines here?
        OpJsonExt.GenerateSFJSON();
        OpJsonExt.getOpportunityJson();
    }
}